workers_dev = true
name = "hono-react-router"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./worker.ts"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "ptu-db"
database_id = "d925390b-d105-40f5-b7bb-a7560065cab7"
migrations_dir = "database/drizzle"

[observability.logs]
enabled = true
